### ISSUE TITLE
Whenever I am giving start location as [0,0,0] or [0,0,0.5] likewise getting error.

### ISSUE THREAD

**Issue by satyamsaha** [Mdhvince/UAV-Autonomous-control#1]
/gym_pybullet_drones/examples/UAV-Autonomous-control/planning/rrt.py", line 215, in _is_path_found
    return goal_node_key in tree.keys()
                            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys

This is the error I am getting

**Comment by Mdhvince** [comment]
Hey,

Can you provide more context so I can reproduce the error you are getting ?

In addition to the start position, could you provide the goal, the number of itération, the max_distance and the obstacles coordinates (if you have some).

Thanks,

**Comment by Mdhvince** [comment]
Also provide the max_distance please.

**Comment by satyamsaha** [comment]
Thanks for responding.

coord_obstacles = [
            [-2, 11, -2, 11, 0, 0.5],  # floor
            [-5.2, -3.8, -3.2, -1.8, -0.2,  1.2],
            [ 3.8,  5.2,  1.8,  3.2, -0.2,  1.2],
            [ 2.8,  4.2, -9.2, -7.8, -0.2,  1.2],
            [-7.2, -5.8, -5.2, -3.8, -0.2,  1.2],
            [-6.2, -4.8,  3.8,  5.2, -0.2,  1.2],
            [-5.2, -3.8, -3.2, -1.8, -0.2,  1.2],
            # ceiling
            [0, 10, 0, 10, 3, 4],
        ]
        
  start_loc = np.array([0, 0, 0])
  goal_loc = [-9.5, 9.5, 2]
  space_limits = [[-10., -10., -10],
                [10, 10, 10]]

max_distance = 1.5

max_iterations = 1000


This informations will help I guess

**Comment by Mdhvince** [comment]
Hi, unfortunately I um not able to reproduce the error you are getting.
